spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orderdbs
    driver-class-name: org.h2.Driver
    username: sa
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

